version: '3.7'

networks:
  backend:
    name: backend
    driver: bridge

services:
  geoserver:
    build:
      context: '.'
    ports:
      - 8082:8080
    environment:
      - docker_app_name=geoserver
      - INITIAL_MEMORY=2G
      - MAXIMUM_MEMORY=4G
      - geoserver_adminpw=admin
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DATABASE=sensrnet
    networks:
      - backend
